Repository miyad927/front-end, pull requests merged in 2024-12, with the labels that each got.

#17 [Feature] 식당 카테고리, 식당 전체 조회 구현
  src/App.vue
  src/main.js
  src/pages/common/components/Header.vue
  src/pages/store/Stores.vue
  src/pages/store/components/BigCategory.vue
  src/pages/store/components/Category.vue
  src/pages/store/components/OrderBox.vue
  src/pages/store/components/SmallCategory.vue
  src/pages/store/components/StoreCard.vue
  src/router/index.js
  src/stores/useCategoryStore.js
  src/stores/useLoadingStore.js
  src/stores/useStoresStore.js
Labels: ✨feature

#21 [Feature] 식당 카테고리 수정, 식당 상세 페이지 - 식당 예약 구현
  package-lock.json
  package.json
  src/main.js
  src/pages/store/StoreDetail.vue
  src/pages/store/Stores.vue
  src/pages/store/components/BigCategory.vue
  src/pages/store/components/Category.vue
  src/pages/store/components/ReservationBox.vue
  src/pages/store/components/SmallCategory.vue
  src/router/index.js
  src/stores/useCategoryStore.js
  src/stores/useReservationStore.js
  src/stores/useStoresStore.js
Labels: ✨feature

#36 [Feature] 식당 상세 페이지 구현
  package-lock.json
  package.json
  src/assets/icons/heart_empty.svg
  src/assets/icons/heart_fill.svg
  src/main.js
  src/pages/store/StoreDetail.vue
  src/pages/store/Stores.vue
  src/pages/store/components/.gitkeep
  src/pages/store/components/ImgCarousel.vue
  src/pages/store/components/ReservationBox.vue
  src/pages/store/components/StoreDescription.vue
  src/pages/store/components/StoreMenuList.vue
  src/pages/store/components/StoreReviewList.vue
  src/stores/.gitkeep
  src/stores/useReviewStore.js
  src/stores/useStoresStore.js
Labels: ✨feature

#37 [Fix] 에러 수정
  src/pages/store/components/SmallCategory.vue
  src/stores/useStoresStore.js
Labels: 🔧Fix

#38 [Feature] 마이페이지 라우트 폴더 구조 구현
  src/pages/common/components/Header.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/client/Client.vue
  src/pages/mypage/client/components/ClientOrder.vue
  src/pages/mypage/seller/Seller.vue
  src/pages/mypage/seller/components/.gitkeep
  src/pages/store/components/StoreCard.vue
  src/router/index.js
Labels: ✨Feature

#40 장바구니 담기 모달 (#39)
  src/pages/product/components/ProductDetail.vue
Labels: ✨Feature

#43 장바구니 조회 페이지
  package-lock.json
  src/assets/cart/cart.css
  src/pages/cart/CartCard.vue
  src/pages/cart/Carts.vue
  src/pages/common/components/Header.vue
  src/router/index.js
  src/stores/useCartStore.js
Labels: ✨Feature

#47 [Feature] 마이페이지 고객 주문 상세 내역 구현
  package-lock.json
  src/pages/mypage/client/Client.vue
  src/pages/mypage/client/ClientOrder.vue
  src/pages/mypage/client/ClientOrderDetail.vue
  src/pages/mypage/client/components/ClientMenu.vue
  src/pages/mypage/client/components/ClientOrder.vue
  src/pages/mypage/client/components/ClientOrderCard.vue
  src/pages/mypage/client/components/ProductItem.vue
  src/router/index.js
  src/stores/useOrderStore.js
Labels: ✨Feature

#56 [Feature] mock server 주소 변경, 식당 조회 필터 구현
  src/pages/mypage/client/ClientOrder.vue
  src/pages/mypage/client/CreateReview.vue
  src/pages/mypage/client/components/ClientMenu.vue
  src/pages/mypage/client/components/ProductItem.vue
  src/pages/store/Stores.vue
  src/pages/store/components/ImgCarousel.vue
  src/pages/store/components/OrderBox.vue
  src/pages/store/components/ReservationBox.vue
  src/pages/store/components/StoreCard.vue
  src/router/index.js
  src/stores/useCategoryStore.js
  src/stores/useOrderStore.js
  src/stores/useReservationStore.js
  src/stores/useReviewStore.js
  src/stores/useStoresStore.js
Labels: 📏Chore, ✨Feature

#57 [feature] Seller 마이페이지 구현
  src/pages/mypage/seller/OrderDetails.vue
  src/pages/mypage/seller/ProductList.vue
  src/pages/mypage/seller/ProductModify.vue
  src/pages/mypage/seller/ProductOrder.vue
  src/pages/mypage/seller/ProductRegister.vue
  src/pages/mypage/seller/Seller.vue
  src/pages/mypage/seller/ShippingRegister.vue
  src/pages/mypage/seller/components/.gitkeep
  src/pages/mypage/seller/components/SellerMenu.vue
  src/router/index.js
  src/stores/useProductsStore.js
Labels: ✨Feature

#59 장바구니 체크 리스트
  src/assets/cart/cart.css
  src/pages/cart/CartCard.vue
  src/pages/cart/Carts.vue
  src/pages/product/Products.vue
Labels: ✨Feature
